"""Added User Col to workout Table

Revision ID: 9fb7972db880
Revises: 34d226434832
Create Date: 2026-06-24 00:23:05.564189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb7972db880'
down_revision: Union[str, Sequence[str], None] = '34d226434832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('workouts', sa.Column('owner', sa.Integer(), nullable=False))
    #op.create_foreign_key(None, 'workouts', 'users', ['owner'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ##op.drop_column('workouts', 'owner')
    # ### end Alembic commands ###
