"""Updated total_workouts to goal_workouts in progress table

Revision ID: c8cfb35f783f
Revises: 4e4176bd9c46
Create Date: 2026-06-24 20:16:58.490996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cfb35f783f'
down_revision: Union[str, Sequence[str], None] = '4e4176bd9c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Progress', sa.Column('goal_workouts', sa.Integer(), nullable=False))
    op.drop_column('Progress', 'total_workouts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Progress', sa.Column('total_workouts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Progress', 'goal_workouts')
    # ### end Alembic commands ###
